//go:build podman

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"go.podman.io/image/v5/pkg/sysregistriesv2"
	"go.podman.io/image/v5/types"
)

// minimalRegistriesConf is a minimal, always-valid (v2-format) registries.conf.
//
// go.podman.io/image (the containers/image-descended library the podman
// backend links against, see backend_podman.go) hard-refuses to load a
// v1-format registries.conf at all — no fallback, no defaults, every
// registry operation (pull/push/inspect/transfer, even login) just fails
// outright. Some real systems still ship one in that legacy format —
// confirmed on every GitHub-hosted ubuntu-24.04[-arm] CI runner as of this
// writing, which is what surfaced this in the first place (the podman e2e
// job's very first run, against a real registry pull, failed with exactly
// this: "registries.conf must be in v2 format but is in v1").
//
// llmman itself needs almost nothing a registries.conf configures
// (unqualified-search-registries rewriting, insecure registries, ...) —
// every reference reaching this backend is already fully qualified by
// the time it gets here (see shortnames.rs's own resolution on the Rust
// side, before ffi::pull/push/etc. is ever called) — so this
// intentionally configures nothing. It just needs to *be* valid v2 TOML,
// so loading it always succeeds regardless of whatever the host's own
// file (if any) looks like. The one thing llmman does configure, the
// mirrors from llmman.conf, goes in a drop-in beside it rather than in
// here — see registrySourceCtx — so this file never has to be rewritten.
const minimalRegistriesConf = `# Minimal, valid (v2-format) registries.conf, generated by llmman itself
# for its own podman backend — see go-shim/registries_podman.go's own doc
# comment for why this exists instead of using the host's
# /etc/containers/registries.conf.
#
# Set CONTAINERS_REGISTRIES_CONF yourself (see containers-registries.conf(5))
# if you want custom mirrors/search registries/etc: llmman will not
# overwrite, or override, an explicitly-set value of that variable.
unqualified-search-registries = []
`

// ensureRegistriesConf points CONTAINERS_REGISTRIES_CONF at llmman's own
// minimalRegistriesConf, unless the user has already set that variable
// themselves (respected, never overwritten — see minimalRegistriesConf's
// own doc comment). go.podman.io/image's sysregistriesv2 package reads
// this env var itself for every SystemContext that doesn't explicitly set
// SystemRegistriesConfPath — which is every SystemContext this backend
// constructs (see backend_podman.go) — so setting it once here, before
// any of them run, is enough; no call site needs to change.
//
// Best-effort: if this fails for any reason (no home directory, an
// unwritable filesystem, ...), it silently leaves CONTAINERS_REGISTRIES_CONF
// unset, falling back to this process's pre-existing behavior of trusting
// the host's own registries.conf, rather than turning a failure to set up
// this one safeguard into a hard failure of every registry operation.
func ensureRegistriesConf() {
	if os.Getenv("CONTAINERS_REGISTRIES_CONF") != "" {
		return
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	// ~/.local/share/llmman — same directory the Rust side already uses
	// for serve.log (see daemon.rs / the CI workflow's own "Show llmman
	// serve.log" step), not a podman-specific location: this file is
	// llmman's own generated default, unrelated to any real podman/
	// skopeo installation's own config.
	dir := filepath.Join(home, ".local", "share", "llmman")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return
	}
	path := filepath.Join(dir, "registries.conf")
	// Only write if missing: never clobber a file that already exists,
	// e.g. one a user has since hand-edited to add their own mirrors.
	if _, err := os.Stat(path); os.IsNotExist(err) {
		if err := os.WriteFile(path, []byte(minimalRegistriesConf), 0o644); err != nil {
			return
		}
	}
	os.Setenv("CONTAINERS_REGISTRIES_CONF", path)
}

func init() {
	ensureRegistriesConf()
}

// ---------------------------------------------------------------------------
// Registry mirrors (see registry_mirrors.go)
// ---------------------------------------------------------------------------

// mirrorsDropIn is the registries.conf.d directory holding the drop-in
// that carries llmman.conf's mirrors to go.podman.io/image; "" when none
// are configured. Named by a hash of its contents under
// ~/.local/share/llmman/registries.conf.d, so two processes with
// different configurations never touch each other's file and the same
// configuration is written once.
var mirrorsDropIn struct {
	mu  sync.Mutex
	dir string
}

// applyRegistryMirrors writes the drop-in for byHost and invalidates
// go.podman.io/image's parsed-config cache, which is keyed by path.
func applyRegistryMirrors(byHost mirrorSet) error {
	mirrorsDropIn.mu.Lock()
	defer mirrorsDropIn.mu.Unlock()
	defer sysregistriesv2.InvalidateCache()

	if len(byHost) == 0 {
		mirrorsDropIn.dir = ""
		return nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("registry mirrors: %w", err)
	}
	base := filepath.Join(home, ".local", "share", "llmman", "registries.conf.d")
	conf := mirrorsRegistriesConf(byHost, mainRegistriesConf(base))
	sum := sha256.Sum256([]byte(conf))
	dir := filepath.Join(base, hex.EncodeToString(sum[:8]))
	path := filepath.Join(dir, "llmman-mirrors.conf")
	if _, err := os.Stat(path); err == nil {
		mirrorsDropIn.dir = dir
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("registry mirrors: %w", err)
	}
	// Write-then-rename: a reader never sees a partial file.
	tmp, err := os.CreateTemp(dir, ".llmman-mirrors-*")
	if err != nil {
		return fmt.Errorf("registry mirrors: %w", err)
	}
	if _, err := tmp.WriteString(conf); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return fmt.Errorf("registry mirrors: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("registry mirrors: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("registry mirrors: %w", err)
	}
	mirrorsDropIn.dir = dir
	return nil
}

// mainRegistriesConf is a context reading only the main registries.conf
// (what CONTAINERS_REGISTRIES_CONF names), for the entries a drop-in has
// to carry forward. A drop-in directory that does not exist reads as none.
func mainRegistriesConf(base string) *types.SystemContext {
	return &types.SystemContext{
		SystemRegistriesConfPath:    os.Getenv("CONTAINERS_REGISTRIES_CONF"),
		SystemRegistriesConfDirPath: filepath.Join(base, "none"),
	}
}

// mirrorsRegistriesConf renders byHost as containers-registries.conf(5)
// `[[registry]]` tables. A drop-in entry replaces the main file's for the
// same prefix, so the main file's own settings for the host (location,
// insecure, blocked, mirror-by-digest-only) are copied over and only the
// mirror list is llmman.conf's. `location` takes no scheme; an http://
// mirror is `insecure = true`.
func mirrorsRegistriesConf(byHost mirrorSet, main *types.SystemContext) string {
	var b strings.Builder
	b.WriteString("# Generated by llmman from llmman.conf's [registries.\"<host>\"] mirrors\n")
	b.WriteString("# and LLMMAN_REGISTRY_MIRRORS; edit those, not this file.\n")
	for _, host := range byHost.hosts() {
		reg := sysregistriesv2.Registry{Prefix: host}
		reg.Location = host
		if base, err := sysregistriesv2.FindRegistry(main, host+"/llmman"); err == nil && base != nil && base.Prefix == host {
			reg = *base
		}
		fmt.Fprintf(&b, "\n[[registry]]\nprefix = %q\nlocation = %q\n", reg.Prefix, reg.Location)
		if reg.Insecure {
			b.WriteString("insecure = true\n")
		}
		if reg.Blocked {
			b.WriteString("blocked = true\n")
		}
		if reg.MirrorByDigestOnly {
			b.WriteString("mirror-by-digest-only = true\n")
		}
		for _, m := range byHost[host] {
			fmt.Fprintf(&b, "\n[[registry.mirror]]\nlocation = %q\n", m.host+m.path)
			if m.scheme == "http" {
				b.WriteString("insecure = true\n")
			}
		}
	}
	return b.String()
}

// registrySourceCtx is the SystemContext for reading from a registry.
// go.podman.io/image skips drop-ins when CONTAINERS_REGISTRIES_CONF is
// set (see go.podman.io/storage/pkg/configfile getSearchPaths) unless the
// main file is also given explicitly, so both are set here. Empty, as
// before, when no mirrors are configured or ctx says withoutMirrors.
func registrySourceCtx(ctx context.Context) *types.SystemContext {
	mirrorsDropIn.mu.Lock()
	dir := mirrorsDropIn.dir
	mirrorsDropIn.mu.Unlock()
	if dir == "" || mirrorsDisabled(ctx) {
		return &types.SystemContext{}
	}
	return &types.SystemContext{
		SystemRegistriesConfPath:    os.Getenv("CONTAINERS_REGISTRIES_CONF"),
		SystemRegistriesConfDirPath: dir,
	}
}
